language: php
sudo: false

php:
  - '7.1'

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="dev-master" SYMFONY_ENV="test" DB=mysql

before_install:
  - mysql -e 'CREATE DATABASE tmtools;'
#  - mysql tmtools < data/sql/tmtools.sql

install:
  - composer install -n

script:
  - php vendor/bin/codecept run unit

notifications:
  email: false