language: php
sudo: false

php:
  - '7.1'

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="dev-master" SYMFONY_ENV="test" DB=postgres

before_install:
  - createdb -O travis tmtools
  - psql tmtools < tests/_data/dump.sql

install:
  - composer install -n

script:
  - php vendor/bin/codecept run

notifications:
  email: false