imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration for Travis CI
doctrine:
    dbal:
        host:     "127.0.0.1"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "travis"
        password: ""