fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix: /api