api_index:
    path: /
    defaults: { _controller: AppBundle:Documentaion:index }

# Employee
api_employee_list:
    path: /employee/list
    defaults: { _controller: AppBundle:EmployeeApi:list }

api_employee_show:
    path: /employee/show/{id}
    defaults: { _controller: AppBundle:EmployeeApi:show }
    requirements:
        id: '\d+'

api_employee_create:
    path: /employee/create
    defaults: { _controller: AppBundle:EmployeeApi:create }
    methods: [POST]

api_employee_update:
    path: /employee/update/{id}
    defaults: { _controller: AppBundle:EmployeeApi:update }
    methods: [POST]
    requirements:
        id: '\d+'

# Document
api_document_list:
    path: /document/list
    defaults: { _controller: AppBundle:DocumentApi:list }

api_document_show:
    path: /document/show/{id}
    defaults: { _controller: AppBundle:DocumentApi:show }
    requirements:
          id: '\d+'

api_document_create:
    path: /document/create
    defaults: { _controller: AppBundle:DocumentApi:create }
    methods: [POST]

api_document_update:
    path: /document/update/{id}
    defaults: { _controller: AppBundle:DocumentApi:update }
    methods: [POST]
    requirements:
        id: '\d+'

api_document_print:
    path: /document/print/{id}
    defaults: { _controller: AppBundle:DocumentApi:print }
    requirements:
          id: '\d+'