homepage:
    path: /
    defaults:
        _controller: "AppBundle:Employee:index"
        path: /employee
        permanent: true

app_employee:
    resource: "@AppBundle/Resources/config/routing/employee.yml"
    prefix:   /employee

