services:
    # App
    app.travel_document:
        class: AppBundle\Service\TravelDocumentService

    # Admin
    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Employees }

    app.admin.employee_job_title:
        class: AppBundle\Admin\EmployeeJobTitleAdmin
        arguments: [~, AppBundle\Entity\EmployeeJobTitle, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Job titles }

    app.admin.company:
        class: AppBundle\Admin\CompanyAdmin
        arguments: [~, AppBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Companies }

    app.admin.travel_document:
        class: AppBundle\Admin\TravelDocumentAdmin
        arguments: [~, AppBundle\Entity\TravelDocument, AppBundle:TravelDocument]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Documents }

    app.admin.travel_destination:
        class: AppBundle\Admin\TravelDestinationAdmin
        arguments: [~, AppBundle\Entity\TravelDestination, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Destinations }

    app.admin.travel_purpose:
        class: AppBundle\Admin\TravelPurposeAdmin
        arguments: [~, AppBundle\Entity\TravelPurpose, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Purposes }

    app.admin.reinbursement_document:
        class: AppBundle\Admin\ReinbursementDocumentAdmin
        arguments: [~, AppBundle\Entity\ReinbursementDocument, AppBundle:ReinbursementDocument]
        tags:
            - { name: sonata.admin, manager_type: orm, group: reinbursement, label: Documents }

    app.admin.reinbursement:
        class: AppBundle\Admin\ReinbursementAdmin
        arguments: [~, AppBundle\Entity\Reinbursement, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: reinbursement, label: Reinbursements }
