services:
    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, AppBundle:EmployeeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: HR, label: Employee }
