services:
    # App
    app.travel_document:
        class: AppBundle\Service\TravelDocumentService

    app.reimbursement_document:
        class: AppBundle\Service\ReimbursementDocumentService

    # Admin
    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Employees }

    app.admin.employee_job_title:
        class: AppBundle\Admin\EmployeeJobTitleAdmin
        arguments: [~, AppBundle\Entity\EmployeeJobTitle, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Job titles }

    app.admin.company:
        class: AppBundle\Admin\CompanyAdmin
        arguments: [~, AppBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: hr, label: Companies }

    app.admin.travel_document:
        class: AppBundle\Admin\TravelDocumentAdmin
        arguments: [~, AppBundle\Entity\TravelDocument, AppBundle:TravelDocument]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Documents }

    app.admin.travel_destination:
        class: AppBundle\Admin\TravelDestinationAdmin
        arguments: [~, AppBundle\Entity\TravelDestination, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Destinations }

    app.admin.travel_purpose:
        class: AppBundle\Admin\TravelPurposeAdmin
        arguments: [~, AppBundle\Entity\TravelPurpose, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: travel, label: Purposes }

    app.admin.reimbursement_document:
        class: AppBundle\Admin\ReimbursementDocumentAdmin
        arguments: [~, AppBundle\Entity\ReimbursementDocument, AppBundle:ReimbursementDocument]
        tags:
            - { name: sonata.admin, manager_type: orm, group: reimbursement, label: Documents }

    app.admin.reimbursement:
        class: AppBundle\Admin\ReimbursementAdmin
        arguments: [~, AppBundle\Entity\Reimbursement, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: reimbursement, label: Reimbursements }

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Users }
