-- MySQL Script generated by MySQL Workbench
-- 11/09/16 16:29:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tmtools
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tmtools` ;

-- -----------------------------------------------------
-- Schema tmtools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tmtools` DEFAULT CHARACTER SET utf8 ;
USE `tmtools` ;

-- -----------------------------------------------------
-- Table `tmtools`.`job_title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tmtools`.`job_title` ;

CREATE TABLE IF NOT EXISTS `tmtools`.`job_title` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `tmtools`.`job_title` (`name` ASC);


-- -----------------------------------------------------
-- Table `tmtools`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tmtools`.`team` ;

CREATE TABLE IF NOT EXISTS `tmtools`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `tmtools`.`team` (`name` ASC);


-- -----------------------------------------------------
-- Table `tmtools`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tmtools`.`employee` ;

CREATE TABLE IF NOT EXISTS `tmtools`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email_address` VARCHAR(255) NOT NULL,
  `birthday` DATE NULL,
  `personal_numeric_code` BIGINT UNSIGNED NULL,
  `identity_card_number` VARCHAR(45) NULL,
  `job_title_id` INT NULL,
  `direct_manager_id` INT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_job_title`
    FOREIGN KEY (`job_title_id`)
    REFERENCES `tmtools`.`job_title` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_employee`
    FOREIGN KEY (`direct_manager_id`)
    REFERENCES `tmtools`.`employee` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `tmtools`.`team` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `tmtools`.`employee` (`username` ASC);
CREATE UNIQUE INDEX `email_address_UNIQUE` ON `tmtools`.`employee` (`email_address` ASC);
CREATE UNIQUE INDEX `personal_numeric_code_UNIQUE` ON `tmtools`.`employee` (`personal_numeric_code` ASC);
CREATE UNIQUE INDEX `identity_card_number_UNIQUE` ON `tmtools`.`employee` (`identity_card_number` ASC);
CREATE INDEX `fk_employee_job_title_idx` ON `tmtools`.`employee` (`job_title_id` ASC);
CREATE INDEX `fk_employee_employee_idx` ON `tmtools`.`employee` (`direct_manager_id` ASC);
CREATE INDEX `fk_employee_team_idx` ON `tmtools`.`employee` (`team_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
